echo off
cls
powershell -command "Get-AppxPackage -allusers *3dbuilder* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *officehub* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *getstarted* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *skypeapp* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *zunemusic* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *windowsmaps* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *solitairecollection* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingfinance* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *zunevideo* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingnews* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *onenote* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *people* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *windowsphone* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingsports* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingweather* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *xboxapp* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *Microsoft.XboxGamingOverlay* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *Microsoft.XboxGameCallableUI* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *SpotifyAB.SpotifyMusic* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *king.com.CandyCrushFriends* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *people* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *commsphone* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *windowsphone* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *phone* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *photos* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingsports* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *sticky* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *sway* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *3d* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *soundrecorder* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *bingweather* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *holographic* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *xbox* | Remove-AppxPackage"
powershell -command "Get-AppxPackage -allusers *windowsstore* | Remove-AppxPackage"
@pause
SteavenToolBox.cmd